### PR TITLE
Issue 106

### PR DESCRIPTION
**Pull request by gainor**

### CODE REVIEW

**Comment by salieflewis** [comment]
Me, pretending I know how to use Radix.

**Comment by gainor** [comment]
> Me, pretending I know how to use Radix.

lol no this is good imo! If we get to a point where we have multiple Sheets with some requiring this functionality of being able to interact with elements outside of the dialog, I think we could more tightly couple modal={false} & these css rules, but since we only have a single usage at this point it feels like a pre-optimization.

**Comment by gainor** [comment]
@losingmyego @salieflewis do we want to keep the overlay + existing *non* clickthrough functionality on mobile (where the dialog is acting as a modal with no click-through events)?

existing:
Screenshot 2023-05-20 at 15 01 59

with click through:
Screenshot 2023-05-20 at 15 01 47

**Comment by salieflewis** [comment]
I think on mobile it makes sense to be able to click through as well. But maybe that depends on how responsive it feels? Lets try to get @losingmyego's thoughts on this, and then get this merged!

**Comment by losingmyego** [comment]
Not sure if I'm understanding this correctly, but the original intention of this modal is that when you click outside of it, it closes automatically. @gainor

**Comment by gainor** [comment]
> Hi!! Thank u for working on this. Not sure if I'm understanding this correctly, but the original intention of this modal was that when you click outside of it, it closes automatically. @gainor
> 
> I don't know if it makes sense to be able to click through the auction when it's partially covered and can be covered more depending on the typefaces the admin selects. If you think it works well down to see
> 
> If we keep the blur - Let's reduce it down 25% from where it is now

Fixed! I agree I think modal type functionality should persist on mobile with no click throughs.

**Review by salieflewis — APPROVED** [review]
Interaction feels great!

**Pull request merged**
