### PR TITLE
Docs

### PR DESCRIPTION
**Pull request by salieflewis**
Hi @Valcoholics opening this as a pull request so that we can see the Vercel deployment! I'll convert it into a draft so it is not merged by accident.

### CODE REVIEW

**Comment by Valcoholics** [comment]
@salieflewis I haven't added a link to the docs on the flexible app itself so you will have to look at it here https://flexible-docs.vercel.app/

**Comment by Valcoholics** [comment]
docs: components page

## Commit   Notes

The documentation should have the same tone consistently, which is "instructional" and "digestible".   Some of these components are less significant than others so I opted out of alphabetical organization and the components organized within context to their state. Composite components at the top, atomic components at the bottom.

## The structure for documenting components 

- Title 
- Description, this needs to match the description from the overview page but here it can further explained. 
- Code block / snippet / Images
- (If needed) Table for props types and descriptions: In addition to listing the properties and arguments the component takes, you can also provide more detailed descriptions of what each prop does and what types of values it accepts. This can help developers ensure that they're passing the correct data to the component. Include If the component has any default values for its properties or arguments. This can help developers understand what values will be used if they don't explicitly set the property or argument themselves.
- Tabs for Usage Examples
- (If needed) Event handlers: If the component has any event handlers (such as onClick or onChange)
- Notes: If there are any limitations or known issues with the component , i.e. "Make sure your app is wrapped in the necessary providers."

## To do: 

format responsive tables 

```
  import { OptionTable } from 'components/table'

<OptionTable options={[
  ['docsRepositoryBase', 'string', 'URL of the documentation repository.'],
]}/>  
```
- This table component is not aligning to the left and there is no padding in the grid cells to keep the text from running into itself.  
- make gif of connecting to wallet for auth check or screenshot before and after for form ui and connect copy

**Comment by Valcoholics** [comment]
https://github.com/public-assembly/flexible/pull/9/commits/59fb0fc7207887ce489e474f5e7e84ea7e3b1edd

https://flexible-docs-gvjl.vercel.app/docs/advanced/components#auctioncountdown

**Comment by Valcoholics** [comment]
Documenting how I solved this problem since the preview is now back, not sure if i would have had the same issue on netlify. 
Nextra/NextJS project builds locally but prerender error when deploying to Vercel. 

https://flexible-docs-git-tailwind-css-valcoholics.vercel.app/docs/advanced/components 

Resources used: 

https://nextjs.org/docs/messages/prerender-error 
https://github.com/shuding/nextra/discussions/1323

Was not a env problem but directly related to exporting page props. 

Made the choice to not add .mdx to `content` in my tailwind.config.js file because it previously broke the deploy for a reason I'm not sure of yet. Renamed my app export file _app.js instead of _app.mdx and It got the job done.

**Comment by salieflewis** [comment]
Docs have been moved into a separate repo, which can be found [here](https://github.com/public-assembly/flexible-docs)

**Pull request closed without merging**
