### PR TITLE
[NOT READY TO MERGE] - first steps towards adding zora testnet (aka chainid 999) support for…

### PR DESCRIPTION
**Pull request by 0xTranqui**
running into some issues with a few imports not working anymore which is confusing since I dont believe any of the code I added would have broken these. got some tips to add in some new config code from [caisson](https://github.com/public-assembly/caisson). will try out and report back

cc @salieflewis @hardyjosh

### CODE REVIEW

**Comment by 0xTranqui** [comment]
errors not showing up in terminal anymore which is maybe a good sign? but still showing up in console.logs in client. passing in (scary looking) screenshots below:

Screenshot 2023-07-29 at 9 58 21 PM

Screenshot 2023-07-29 at 9 58 36 PM

**Comment by 0xTranqui** [comment]
ahhh I believe its because I need to update builder utils first. doing that now

**Comment by 0xTranqui** [comment]
@salieflewis i think we are ok to merge this -- only question to you before I do is do you think its worth adding the zora mainnet stuff to this as well to keep things tidier? is only a few more lines of code

**Comment by hardyjosh** [comment]
@0xTranqui @salieflewis did you decide what you wanted to do here? Would be cool to get the ENERGY fork live, lmk if I can help!

**Comment by 0xTranqui** [comment]
@hardyjosh im gonna merge this and then quick follow with zora mainnet + base support. i wont have capacity to actually run a live interface so if ur willing to take that on that would be super helpful

**Pull request merged**
